# Generated by Django 5.2.5 on 2026-03-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_code_product_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma separated colors e.g. Black, Red, White', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=20),
        ),
    ]
